id: IF2A1F71E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T06:45:53+00:00'
last_modified: '2022-06-08T08:45:56.829112+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG02390
  title: གསུང་འབུམ། བསོད་ནམས་རྒྱལ་མཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EF9C:
      image_group_id: I00KG03389
      title: ''
      total_pages: 938
      order: 1
      base_file: EF9C.txt
    186A:
      image_group_id: I00KG03390
      title: ''
      total_pages: 2
      order: 2
      base_file: 186A.txt
    '5146':
      image_group_id: I00KG03391
      title: ''
      total_pages: 896
      order: 3
      base_file: 5146.txt
    683B:
      image_group_id: I00KG03392
      title: ''
      total_pages: 528
      order: 4
      base_file: 683B.txt
    '8911':
      image_group_id: I00KG03393
      title: ''
      total_pages: 938
      order: 5
      base_file: 8911.txt
    '7268':
      image_group_id: I00KG03394
      title: ''
      total_pages: 2
      order: 6
      base_file: 7268.txt
    82A8:
      image_group_id: I00KG03395
      title: ''
      total_pages: 2
      order: 7
      base_file: 82A8.txt
    59E0:
      image_group_id: I00KG03396
      title: ''
      total_pages: 50
      order: 8
      base_file: 59E0.txt
    12EC:
      image_group_id: I00KG03397
      title: ''
      total_pages: 320
      order: 9
      base_file: 12EC.txt
    FFCB:
      image_group_id: I00KG03398
      title: ''
      total_pages: 48
      order: 10
      base_file: FFCB.txt
    DAA3:
      image_group_id: I00KG03399
      title: ''
      total_pages: 956
      order: 11
      base_file: DAA3.txt
    52A2:
      image_group_id: I00KG03400
      title: ''
      total_pages: 204
      order: 12
      base_file: 52A2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
