id: IF2A1F71E
legacy_id: P009120
ocr_import_info:
  bdrc_scan_id: W00KG02390
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T06:43:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T11:43:54.962519+00:00'
last_modified: 2022-08-29 19:53:33.067700
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG02390
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00KG02390
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བསོད་ནམས་རྒྱལ་མཚན།
  author: བླ་མ་དམ་པ་བསོད་ནམས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.5656658018658863
  ocr_word_median_confidence_index: 0.5699999928474426
quality: null
bases:
  I00KG03390:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03390
      total_pages: 2
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00KG03390.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8946905568096459
    legacy_id: v002
  I00KG03395:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03395
      total_pages: 2
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I00KG03395.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8946103929699242
    legacy_id: v007
  I00KG03394:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03394
      total_pages: 2
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I00KG03394.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.897166126519927
    legacy_id: v006
  I00KG03397:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03397
      total_pages: 320
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I00KG03397.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5238716867394095
    legacy_id: v009
  I00KG03398:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03398
      total_pages: 48
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I00KG03398.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6154350570252545
    legacy_id: v010
  I00KG03389:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03389
      total_pages: 938
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03389.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5246163062057134
    legacy_id: v001
  I00KG03396:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03396
      total_pages: 50
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I00KG03396.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.659276551222889
    legacy_id: v008
  I00KG03392:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03392
      total_pages: 528
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I00KG03392.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5665334830610502
    legacy_id: v004
  I00KG03399:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03399
      total_pages: 956
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I00KG03399.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5547046185301389
    legacy_id: v011
  I00KG03391:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03391
      total_pages: 896
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00KG03391.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6274591590879542
    legacy_id: v003
  I00KG03400:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03400
      total_pages: 204
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I00KG03400.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5864761176206437
    legacy_id: v012
  I00KG03393:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03393
      total_pages: 938
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I00KG03393.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5663934407353088
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
