id: P009120
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00KG02390
  title: གསུང་འབུམ། བསོད་ནམས་རྒྱལ་མཚན།
  author: ''
  volumes:
    c95192c9fd2a4107af4db7ecca7931d1:
      image_group_id: I00KG03389
      title: ''
      volume_number: 1
      total_pages: 938
      base_file: v001.txt
    9e5d74afe69a40799b0458d3cc422c98:
      image_group_id: I00KG03390
      title: ''
      volume_number: 2
      total_pages: 2
      base_file: v002.txt
    7a5d1494a5b840429f4355be9858faa2:
      image_group_id: I00KG03391
      title: ''
      volume_number: 3
      total_pages: 896
      base_file: v003.txt
    4f85560cacc54f08a505762f67ea9c55:
      image_group_id: I00KG03392
      title: ''
      volume_number: 4
      total_pages: 528
      base_file: v004.txt
    e6c106d8cfae4788bdcbca73365575c3:
      image_group_id: I00KG03393
      title: ''
      volume_number: 5
      total_pages: 938
      base_file: v005.txt
    49cd7d9f92b54d42a3f51a4ad6a5af2c:
      image_group_id: I00KG03394
      title: ''
      volume_number: 6
      total_pages: 2
      base_file: v006.txt
    7f154b75335d494e95cc37940c52ad0d:
      image_group_id: I00KG03395
      title: ''
      volume_number: 7
      total_pages: 2
      base_file: v007.txt
    776154e689ca42978db828834b7c82ec:
      image_group_id: I00KG03396
      title: ''
      volume_number: 8
      total_pages: 50
      base_file: v008.txt
    ae553ebc82044e9293d80b9e24686623:
      image_group_id: I00KG03397
      title: ''
      volume_number: 9
      total_pages: 320
      base_file: v009.txt
    d373d05875d343878bb8421cae4d09f0:
      image_group_id: I00KG03398
      title: ''
      volume_number: 10
      total_pages: 48
      base_file: v010.txt
    e287f2cd9c1040b3bb3d8d5909c3d794:
      image_group_id: I00KG03399
      title: ''
      volume_number: 11
      total_pages: 956
      base_file: v011.txt
    52772fc5e9b346a79948f9fd00daa691:
      image_group_id: I00KG03400
      title: ''
      volume_number: 12
      total_pages: 204
      base_file: v012.txt
